FUL-5009: Namespaces are now not used to toggle resources public/not …
beekpr/wsgiservice-restplus pull request #10
Opened 2017-03-06 11:50 UTC by philthyharry

2017-03-15 08:56 UTC, philthyharry commented
@Wattos and @alexanderjulo Have a look at this suggestion, I think it makes sense to fix that.

2017-03-15 12:53 UTC, Wattos commented
@philthyharry Please create new bug which describes the problem in this. You have linked this to a Story which is already done, so it does not make sense to add code to that ticket

2017-03-15 12:54 UTC, Wattos requested changes
Please see comment

2017-03-22 07:27 UTC, Wattos commented
@philthyharry what is the state of this?

2017-03-22 07:36 UTC, philthyharry commented
@Wattos Oh, I was waiting for your review, seems I missed your previous comment! I'll fire a bug first, then will get back to you.

2017-03-31 11:21 UTC, philthyharry commented
@Wattos - its now linked to the new bug ticket - please review, thanks!

2017-04-03 06:53 UTC, Wattos commented
I would close this for now. I think the behaviour is OK like this

2017-04-03 06:53 UTC, closed without merging