FUL-5009: Ability to restrict resources for internal use only
beekpr/wsgiservice-restplus pull request #9
Opened 2017-03-02 12:50 UTC by philthyharry

Namespaces or route() method can now be given internal=True parameter to restrict the namespace/resource for internal display only. With some resources annotated as internal /api/2/swagger.json will return the api spec without listing those resources, unless ?internal=true is passed along with the request: 

`/api/2/swagger.json?internal=true`

2017-03-02 15:03 UTC, Wattos requested changes
Small comments from my side, then it is good!

2017-03-02 15:03 UTC, Wattos commented on wsgiservice_restplus/api.py
> +            show_internal = False
```python
show_internal = (unicode(internal) or "").lower() == "true"
```

2017-03-02 15:03 UTC, Wattos commented on wsgiservice_restplus/swagger.py
> +                if show_internal or not resource.internal:
```python
  if not show_internal and resource.internal:
     continue
```

2017-03-02 15:03 UTC, Wattos commented on wsgiservice_restplus/swagger.py
> +            'host': None,       #NOTE: removed get_host() as not used.
remove the comment or say something which makes sense

2017-03-02 15:14 UTC, philthyharry commented on wsgiservice_restplus/swagger.py
> +            'host': None,       #NOTE: removed get_host() as not used.
How about `#Note: something which makes sense.`? 
;P

2017-03-02 15:38 UTC, philthyharry commented
@Wattos its back to you for approval

2017-03-02 20:26 UTC, Wattos commented on wsgiservice_restplus/namespace.py
> +            cls.internal = kwargs.get('internal', False)
This is dangerous and we should avoid this. Instead we should perform this in `add_resource`.

The problem is that we are adding a property to the class. We could potentially overwrite an existing property called "internal"

2017-03-02 20:28 UTC, Wattos commented on wsgiservice_restplus/swagger.py
> +                if resource.internal and not show_internal:
use `kwargs.get('internal')` instead of `resource.internal` as mentioned before

2017-03-02 20:30 UTC, Wattos commented
I added 2 more coments. In addition, I think we should change the `internal` key on the namespace and route to `public`. This is because we should explicitly mark API as public as we need to be careful there.

Please keep the `internal` key on the SwaggerResource.

2017-03-02 20:31 UTC, Wattos commented on examples/general/simple2.py
> +    internal=False
please use `public=True` instead

2017-03-02 20:31 UTC, Wattos commented on examples/general/simple2.py
> +@ping_ns.route('/testball', internal=True)
either public=False or nothing at all

2017-03-02 20:32 UTC, Wattos commented on wsgiservice_restplus/swagger.py
> +                if resource.internal and not show_internal:
`kwarge.get('public', False)` instead of `internal`. This is better design

2017-03-02 20:33 UTC, Wattos commented on wsgiservice_restplus/api.py
> +            show_internal = (unicode(internal) or "").lower() == "true"
this is OK like this. We should **not** change this to public

2017-03-03 22:20 UTC, philthyharry commented
@Wattos I switched the internal=True logic to public=False and tested it again and it works. Cheers.

2017-03-04 06:12 UTC, Wattos approved these changes
Please change the defaults of public to `False` and then we are good. I am going to approve it, so that you can merge this after you have done the change

2017-03-04 06:12 UTC, Wattos commented on wsgiservice_restplus/namespace.py
> +        self.public = kwargs.get('public', True)
default of public should be `False`. This should be an opt in operation

2017-03-04 06:12 UTC, Wattos commented on wsgiservice_restplus/namespace.py
> +        resource.public = kwargs.get('public', True)
default of public should be `False`

2017-03-04 06:12 UTC, Wattos commented
Please change the default of public to `False` and then we can merge.

2017-03-04 06:13 UTC, Wattos commented
The endpoints which will be public need then be shown explicitly over `public=True`. Providing a whitelist is much better than a blacklist in this case

2017-03-05 10:03 UTC, philthyharry commented
Thanks @Wattos for review, I reverted the defaults to public=False, for resources and namespaces and tested, works well (fyi check examples/general/sample2.py), thus will merge.

2017-03-05 10:04 UTC, merged